#!/bin/bash
set -e
cd $1
echo $PWD
echo "git pull origin master"
git pull origin master

echo "composer install"
composer install

echo "php artisan migrate"
php artisan migrate

echo "php artisan db:seed"
php artisan db:seed

echo "php artisan clear-compiled"
php artisan clear-compiled

echo "php artisan optimize"
php artisan optimize
